"""The SoulFire SDK automates Minecraft bots with lazy Effect operations.

Start with the `Python tutorial <https://soulfiremc.com/docs/sdk/python>`_.
Keep bot operations inside a scope and run the complete workflow at its boundary.

Methods decorated with ``@fn`` return lazy ``Effect`` operations when called.
Their source signatures use ``EffectGen`` to describe the generator implementation.
"""

from ._install import LocalSoulFireServer
from .actions import SoulFireActionError
from .admin import SoulFireAdmin
from .behaviors import (
    AttackNearest,
    AutoArmor,
    AutoEat,
    AutoRespawn,
    AutoTotem,
    BotBehavior,
    Build,
    BuildPlacement,
    CollectBlocks,
    FollowEntity,
    FunctionBehavior,
    SoulFireBehaviorError,
    SoulFireBehaviorTimeoutError,
    cleanup,
    conditional,
    define_behavior,
    fallback,
    parallel,
    race,
    repeat,
    retry,
    run_behaviors,
    scoped_lease,
    sequence,
    timeout,
    until,
)
from .bot import SoulFireBot, SoulFireBotControlLease
from .bot_live_pb2 import (
    BotChunkEvent,
    BotEvent,
    BotEventFilter,
    BotResourcePackEvent,
    BotTitleEvent,
    ChunkEventKind,
    CreativeItemStack,
    ResourcePackEventKind,
    ResourcePackResponse,
    TitleEventKind,
    WaitForChunksResponse,
)
from .camera import CameraRenderOptions, SoulFireCamera, WorldMapOptions, decode_camera_image
from .client import (
    ManagedInstallOptions,
    SoulFire,
    SoulFireInstance,
    SoulFireService,
    connection_layer,
)
from .common_pb2 import BlockPosition, WorldPosition
from .connection import (
    SDK_API_VERSION,
    SDK_VERSION,
    CapabilitySet,
    RequiredPlugin,
    ServerMetadata,
    SoulFireCapabilityError,
    SoulFireCompatibilityError,
)
from .domain_pb2 import (
    BlockSnapshot,
    EntityReference,
    EntitySnapshot,
    ItemStackSnapshot,
    PlayerSnapshot,
    TextComponent,
    Vec3,
)
from .errors import (
    RpcFailureContext,
    SoulFireInstallError,
    SoulFireOperationError,
    SoulFireRpcError,
    SoulFireStateError,
    SoulFireTimeoutError,
    SoulFireValidationError,
)
from .example_plugin import ExamplePluginClient, example_plugin
from .fleet import (
    FleetAssignment,
    FleetBot,
    FleetMetadataSelector,
    FleetOperationOutcome,
    FleetOperationReport,
    FleetPoint,
    FleetRadius,
    FleetSelector,
    FleetTaskGroupError,
    FleetTaskMember,
    FleetTaskOutcome,
    FleetTaskReport,
    FleetTaskStartFailure,
    FleetTaskStartOptions,
    FleetTaskStreamEvent,
    SoulFireFleet,
    SoulFireFleetTaskGroup,
)
from .instance_live_pb2 import InstanceEvent, InstanceEventFilter
from .pathfinding import BlockTarget, EntityTarget, Goals, SoulFirePathfinder, WorldTarget, goals
from .plugin_api_pb2 import (
    PluginPermissionDefault,
    PluginPermissionDescriptor,
    PluginPermissionRisk,
    PluginPermissionScope,
)
from .plugins import (
    PluginCatalog,
    ReflectiveMessage,
    ReflectivePlugin,
    ReflectivePluginEvent,
    SoulFirePluginCompatibilityError,
    SoulFirePluginDescriptorError,
    SoulFirePluginModule,
    SoulFirePluginNotFoundError,
    TypedPluginEvent,
)
from .protocol import SoulFireProtocol
from .protocol_pb2 import (
    PACKET_DIRECTION_CLIENTBOUND,
    PACKET_DIRECTION_SERVERBOUND,
    BotProtocolInfo,
    PacketDirection,
    PacketSchema,
    RawPacketEvent,
)
from .selectors import item_selector
from .semantic import (
    ChatMatch,
    ChatMatcher,
    InventoryRankingOptions,
    SoulFireChat,
    SoulFireContainer,
    SoulFireContainerClosedError,
    SoulFireInventory,
    SoulFireRecipes,
    SoulFireRegistry,
    SoulFireWorld,
    match_chat,
)
from .session import (
    BotBossBarState,
    BotEnvironmentState,
    BotScoreboardObjective,
    BotScoreboardScore,
    BotScoreboardState,
    BotScoreboardTeam,
    BotSession,
    BotSessionOptions,
    BotSessionState,
    empty_bot_session_state,
    reduce_bot_session_state,
)
from .streams import Stream
from .tasks import (
    ContainerTransferSpec,
    LoadoutRequirementSpec,
    SchematicBlock,
    SoulFireTask,
    SoulFireTaskError,
    SoulFireTasks,
    is_terminal_task_status,
)
from .user_pb2 import UserPluginPermissionGrant
from .world_pb2 import (
    BlockSelector,
    BoxRegion,
    CanSeeBlockResponse,
    EntitySelector,
    EstimateDigTimeResponse,
    EstimateExplosionDamageResponse,
    GetWorldBlockResponse,
    GetWorldEntityResponse,
    QueryBlocksResponse,
    QueryEntitiesResponse,
    QueryRegion,
    QuerySort,
    RaycastResponse,
    SphereRegion,
)

__all__ = [
    "PACKET_DIRECTION_CLIENTBOUND",
    "PACKET_DIRECTION_SERVERBOUND",
    "SDK_API_VERSION",
    "SDK_VERSION",
    "AttackNearest",
    "AutoArmor",
    "AutoEat",
    "AutoRespawn",
    "AutoTotem",
    "BlockPosition",
    "BlockSelector",
    "BlockSnapshot",
    "BlockTarget",
    "BotBehavior",
    "BotBossBarState",
    "BotChunkEvent",
    "BotEnvironmentState",
    "BotEvent",
    "BotEventFilter",
    "BotProtocolInfo",
    "BotResourcePackEvent",
    "BotScoreboardObjective",
    "BotScoreboardScore",
    "BotScoreboardState",
    "BotScoreboardTeam",
    "BotSession",
    "BotSessionOptions",
    "BotSessionState",
    "BotTitleEvent",
    "BoxRegion",
    "Build",
    "BuildPlacement",
    "CameraRenderOptions",
    "CanSeeBlockResponse",
    "CapabilitySet",
    "ChatMatch",
    "ChatMatcher",
    "ChunkEventKind",
    "CollectBlocks",
    "ContainerTransferSpec",
    "CreativeItemStack",
    "EntityReference",
    "EntitySelector",
    "EntitySnapshot",
    "EntityTarget",
    "EstimateDigTimeResponse",
    "EstimateExplosionDamageResponse",
    "ExamplePluginClient",
    "FleetAssignment",
    "FleetBot",
    "FleetMetadataSelector",
    "FleetOperationOutcome",
    "FleetOperationReport",
    "FleetPoint",
    "FleetRadius",
    "FleetSelector",
    "FleetTaskGroupError",
    "FleetTaskMember",
    "FleetTaskOutcome",
    "FleetTaskReport",
    "FleetTaskStartFailure",
    "FleetTaskStartOptions",
    "FleetTaskStreamEvent",
    "FollowEntity",
    "FunctionBehavior",
    "GetWorldBlockResponse",
    "GetWorldEntityResponse",
    "Goals",
    "InstanceEvent",
    "InstanceEventFilter",
    "InventoryRankingOptions",
    "ItemStackSnapshot",
    "LoadoutRequirementSpec",
    "LocalSoulFireServer",
    "ManagedInstallOptions",
    "PacketDirection",
    "PacketSchema",
    "PlayerSnapshot",
    "PluginCatalog",
    "PluginPermissionDefault",
    "PluginPermissionDescriptor",
    "PluginPermissionRisk",
    "PluginPermissionScope",
    "QueryBlocksResponse",
    "QueryEntitiesResponse",
    "QueryRegion",
    "QuerySort",
    "RawPacketEvent",
    "RaycastResponse",
    "ReflectiveMessage",
    "ReflectivePlugin",
    "ReflectivePluginEvent",
    "RequiredPlugin",
    "ResourcePackEventKind",
    "ResourcePackResponse",
    "RpcFailureContext",
    "SchematicBlock",
    "ServerMetadata",
    "SoulFire",
    "SoulFireActionError",
    "SoulFireAdmin",
    "SoulFireBehaviorError",
    "SoulFireBehaviorTimeoutError",
    "SoulFireBot",
    "SoulFireBotControlLease",
    "SoulFireCamera",
    "SoulFireCapabilityError",
    "SoulFireChat",
    "SoulFireCompatibilityError",
    "SoulFireContainer",
    "SoulFireContainerClosedError",
    "SoulFireFleet",
    "SoulFireFleetTaskGroup",
    "SoulFireInstallError",
    "SoulFireInstance",
    "SoulFireInventory",
    "SoulFireOperationError",
    "SoulFirePathfinder",
    "SoulFirePluginCompatibilityError",
    "SoulFirePluginDescriptorError",
    "SoulFirePluginModule",
    "SoulFirePluginNotFoundError",
    "SoulFireProtocol",
    "SoulFireRecipes",
    "SoulFireRegistry",
    "SoulFireRpcError",
    "SoulFireService",
    "SoulFireStateError",
    "SoulFireTask",
    "SoulFireTaskError",
    "SoulFireTasks",
    "SoulFireTimeoutError",
    "SoulFireValidationError",
    "SoulFireWorld",
    "SphereRegion",
    "Stream",
    "TextComponent",
    "TitleEventKind",
    "TypedPluginEvent",
    "UserPluginPermissionGrant",
    "Vec3",
    "WaitForChunksResponse",
    "WorldMapOptions",
    "WorldPosition",
    "WorldTarget",
    "cleanup",
    "conditional",
    "connection_layer",
    "decode_camera_image",
    "define_behavior",
    "empty_bot_session_state",
    "example_plugin",
    "fallback",
    "goals",
    "is_terminal_task_status",
    "item_selector",
    "match_chat",
    "parallel",
    "race",
    "reduce_bot_session_state",
    "repeat",
    "retry",
    "run_behaviors",
    "scoped_lease",
    "sequence",
    "timeout",
    "until",
]
