# Generated from soulfire/pov.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.11.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .pov_pb2 import PovFrame, PovInputRequest, PovInputResponse, PovWatchRequest

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class PovService(Protocol):
    def watch(self, request: PovWatchRequest, ctx: RequestContext[PovWatchRequest, PovFrame]) -> AsyncIterator[PovFrame]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def input(self, request: PovInputRequest, ctx: RequestContext[PovInputRequest, PovInputResponse]) -> PovInputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PovServiceASGIApplication(ConnectASGIApplication[PovService]):
    def __init__(
        self,
        service: PovService | AsyncGenerator[PovService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/soulfire.v1.PovService/Watch": Endpoint.server_stream(
                    method=MethodInfo(
                        name="Watch",
                        service_name="soulfire.v1.PovService",
                        input=PovWatchRequest,
                        output=PovFrame,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.watch,
                ),
                "/soulfire.v1.PovService/Input": Endpoint.unary(
                    method=MethodInfo(
                        name="Input",
                        service_name="soulfire.v1.PovService",
                        input=PovInputRequest,
                        output=PovInputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.input,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.PovService"


class PovServiceClient(ConnectClient):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def watch(
        self,
        request: PovWatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> AsyncIterator[PovFrame]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Watch",
                service_name="soulfire.v1.PovService",
                input=PovWatchRequest,
                output=PovFrame,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def input(
        self,
        request: PovInputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PovInputResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Input",
                service_name="soulfire.v1.PovService",
                input=PovInputRequest,
                output=PovInputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

class PovServiceSync(Protocol):
    def watch(self, request: PovWatchRequest, ctx: RequestContext[PovWatchRequest, PovFrame]) -> Iterator[PovFrame]:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def input(self, request: PovInputRequest, ctx: RequestContext[PovInputRequest, PovInputResponse]) -> PovInputResponse:
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class PovServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: PovServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = None,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/soulfire.v1.PovService/Watch": EndpointSync.server_stream(
                    method=MethodInfo(
                        name="Watch",
                        service_name="soulfire.v1.PovService",
                        input=PovWatchRequest,
                        output=PovFrame,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.watch,
                ),
                "/soulfire.v1.PovService/Input": EndpointSync.unary(
                    method=MethodInfo(
                        name="Input",
                        service_name="soulfire.v1.PovService",
                        input=PovInputRequest,
                        output=PovInputResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.input,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/soulfire.v1.PovService"


class PovServiceClientSync(ConnectClientSync):
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def watch(
        self,
        request: PovWatchRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> Iterator[PovFrame]:
        return self.execute_server_stream(
            request=request,
            method=MethodInfo(
                name="Watch",
                service_name="soulfire.v1.PovService",
                input=PovWatchRequest,
                output=PovFrame,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def input(
        self,
        request: PovInputRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> PovInputResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Input",
                service_name="soulfire.v1.PovService",
                input=PovInputRequest,
                output=PovInputResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
