site_name: !ENV [SOULFIRE_REFERENCE_NAME, SoulFire Python SDK]
site_url: https://py.soulfiremc.com/
repo_url: https://github.com/soulfiremc-com/SoulFire
edit_uri: blob/main/sdk/python/src/
docs_dir: python-docs
site_dir: dist/python
theme:
  name: material
  logo: https://soulfiremc.com/logo.png
  features:
    - navigation.indexes
    - search.highlight
    - content.action.view
nav:
  - Overview: index.md
  - API: api/
  - Guides: https://soulfiremc.com/docs/sdk/python
  - TypeScript API: https://ts.soulfiremc.com/
plugins:
  - search
  - gen-files:
      scripts:
        - python-pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [../python/src]
          options:
            allow_inspection: false
            docstring_style: google
            members_order: source
            show_if_no_docstring: true
            members: true
            filters: ["!^_"]
            show_root_heading: true
            show_source: true
            show_signature_annotations: true
            show_submodules: false
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
