name: Docker Deploy
on: [ workflow_dispatch, workflow_call ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.ref }}
      - name: Get version
        id: get-version
        run: |
          projectVersion=$(grep '^maven_version=' gradle.properties | cut -d'=' -f2)
          echo "version=$projectVersion" >> $GITHUB_OUTPUT
      - name: "Login to Docker Container Registry"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
        with:
          driver: docker-container
          driver-opts: |
            image=moby/buildkit:v0.11.6
          platforms: linux/amd64,linux/arm64
      - name: Build and Push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            VERSION=${{ steps.get-version.outputs.version }}
          tags: |
            alexprogrammerde/soulfire:latest
            alexprogrammerde/soulfire:${{ steps.get-version.outputs.version }}
            ghcr.io/soulfiremc-com/soulfire:latest
            ghcr.io/soulfiremc-com/soulfire:${{ steps.get-version.outputs.version }}
          annotations: |
            index:org.opencontainers.image.source=https://github.com/soulfiremc-com/SoulFire
            index:org.opencontainers.image.description=Advanced Minecraft Bot Tool. Deploy bots for testing, automation, and server development.
            index:org.opencontainers.image.licenses=AGPL-3.0-only
            index:org.opencontainers.image.title=SoulFire
            index:org.opencontainers.image.vendor=AlexProgrammerDE
      - name: Push README.md to Dockerhub
        uses: christian-korneck/update-container-description-action@d36005551adeaba9698d8d67a296bd16fa91f8e8 # v1
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: alexprogrammerde/soulfire
          provider: dockerhub
          short_description: 'Advanced Minecraft Bot Tool. Deploy bots for testing, automation, and server development.'
          readme_file: 'README.md'
