name: Set Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to set'
        required: true
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  set-version:
    name: Set Version

    permissions:
      contents: write
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: 'Shared: Checkout repository'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.ref }}

      - name: 'Set Version'
        run: |
          sed -i 's/^maven_version=.*/maven_version='"${INPUTS_VERSION}"'/g' gradle.properties
        env:
          INPUTS_VERSION: ${{ inputs.version }}

      - name: 'Commit Version'
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: 'chore(release): bump version to ${{ inputs.version }}'
